services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${SPHINX_DATABASE__PASSWORD:-password}
      POSTGRES_USER: ${SPHINX_DATABASE__USER:-postgres}
      POSTGRES_PORT: ${SPHINX_DATABASE__PORT:-5432}
      POSTGRES_HOST: ${SPHINX_DATABASE__HOST:-localhost}
      POSTGRES_DB: ${SPHINX__DATABASE_NAME:-postgres}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -h $${POSTGRES_HOST}"]
      interval: 5s
      timeout: 5s
      retries: 10
