services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  # sphinx:
  #   build: .
  #   container_name: sphinx-server
  #   ports:
  #     - ${SPHINX_APPLICATION__PORT:-3333}:${SPHINX_APPLICATION__PORT:-3333}
  #   environment:
  #     # sphinx 
  #     SPHINX_APPLICATION__HOST: ${SPHINX_APPLICATION__HOST:-0.0.0.0}
  #     SPHINX_APPLICATION__PORT: ${SPHINX_APPLICATION__PORT:-3333}
  #     # database
  #     SPHINX_DATABASE__PASSWORD: ${SPHINX_DATABASE__PASSWORD:-password}
  #     SPHINX_DATABASE__USER: ${SPHINX_DATABASE__USER:-postgres}
  #     SPHINX_DATABASE__PORT: ${SPHINX_DATABASE__PORT:-5432}
  #     SPHINX_DATABASE__HOST: ${SPHINX_DATABASE__HOST:-localhost}
  #     SPHINX_DATABASE__NAME: ${SPHINX__DATABASE_NAME:-postgres}
  #     SPHINX_DATABASE__REQUIRE_SSL: ${SPHINX_DATABASE__REQUIRE_SSL:-false}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${SPHINX_DATABASE__PASSWORD:-password}
      POSTGRES_USER: ${SPHINX_DATABASE__USER:-postgres}
      POSTGRES_PORT: ${SPHINX_DATABASE__PORT:-5432}
      POSTGRES_HOST: ${SPHINX_DATABASE__HOST:-localhost}
      POSTGRES_DB: ${SPHINX__DATABASE_NAME:-postgres}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -h $${POSTGRES_HOST}"]
      interval: 5s
      timeout: 5s
      retries: 10
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 1231:80
