application:
  host: 0.0.0.0
  port: 3333
  config: 
    allow_unverified: false
    reset_password:
      callback: http://0.0.0.0:3333/reset-password/callback
      token_expiration_secs: 3600
    confirm_email:
      callback: http://0.0.0.0:3333/verify-email/callback
      token_expiration_secs: 3600
database:
  user: postgres
  port: 5432
  host: localhost
  name: postgres
  require_ssl: false
redis:
  url: redis://127.0.0.1:6379
jwt:
  iss: sphinx
  aud: ["sphinx-users"] 
  access_token:
    exp_duration_secs: 600 # 10 minutes
  refresh_token:
    exp_duration_secs: 2592000 # 30 days
  default_token:
    exp_duration_secs: 86400 # 1 day
oauth:
  callback: http://0.0.0.0:3333/
  discord:
    auth_url: https://discord.com/api/oauth2/authorize?response_type=code
    token_url: https://discord.com/api/oauth2/token
    redirect_url: http://localhost:3333/oauth/discord/callback
  google:
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    token_url: https://www.googleapis.com/oauth2/v3/token
    redirect_url: http://localhost:3333/oauth/google/callback
  github:
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    redirect_url: http://localhost:3333/oauth/github/callback
smtp:
  url: live.smtp.mailtrap.io 
  username: api
  mailbox:
    email: mailtrap@demomailtrap.com
    name: Sphinx
